Manga Chapters Calculator/Controllers/HomeController.cs
using Manga_Chapters_Calculator.DAL;
using Manga_Chapters_Calculator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Manga_Chapters_Calculator.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            MangaContext db = new MangaContext();
            List<MangaFamily> families = new List<MangaFamily>(db.MangaFamilies);
            families.Insert(0, new MangaFamily() { ID = -1, Name = " " });

            List<Manga> defaultMangas = new List<Manga>();
            defaultMangas.Add(new Manga() { ID = -1, Name = " " } );

            ViewData["families"] = new SelectList(families, "ID", "Name");
            ViewData["mangas"] = new SelectList(defaultMangas, "ID", "Name");

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        public ActionResult Mangas(int familyId)
        {
            MangaContext db = new MangaContext();
            List<Manga> mangas = new List<Manga>(db.Mangas.Where(x => x.MangaFamilyID == familyId));
            mangas.Sort((x, y) => x.PartNo.CompareTo(y.PartNo));
            mangas.Insert(0, new Manga() { ID = -1, Name = " " });

            return Json(
                mangas.Select(x => new
                {
                    Id = x.ID,
                    Name = x.Name
                })
                , JsonRequestBehavior.AllowGet
            );
        }
    }
}

Manga Chapters Calculator/Controllers/MangaFamiliesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Manga_Chapters_Calculator.Models;
using Manga_Chapters_Calculator.DAL;

namespace Manga_Chapters_Calculator.Controllers
{
    public class MangaFamiliesController : Controller
    {
        private MangaContext db = new MangaContext();

        // GET: MangaFamilies
        public ActionResult Index()
        {
            return View(db.MangaFamilies.ToList());
        }

        // GET: MangaFamilies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MangaFamily mangaFamily = db.MangaFamilies.Find(id);
            if (mangaFamily == null)
            {
                return HttpNotFound();
            }
            return View(mangaFamily);
        }

        // GET: MangaFamilies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MangaFamilies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] MangaFamily mangaFamily)
        {
            if (ModelState.IsValid)
            {
                db.MangaFamilies.Add(mangaFamily);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mangaFamily);
        }

        // GET: MangaFamilies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MangaFamily mangaFamily = db.MangaFamilies.Find(id);
            if (mangaFamily == null)
            {
                return HttpNotFound();
            }
            return View(mangaFamily);
        }

        // POST: MangaFamilies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] MangaFamily mangaFamily)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mangaFamily).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mangaFamily);
        }

        // GET: MangaFamilies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MangaFamily mangaFamily = db.MangaFamilies.Find(id);
            if (mangaFamily == null)
            {
                return HttpNotFound();
            }
            return View(mangaFamily);
        }

        // POST: MangaFamilies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MangaFamily mangaFamily = db.MangaFamilies.Find(id);
            db.MangaFamilies.Remove(mangaFamily);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult GetLocalChapter(int chapterGlobal, int familyId)
        {
            int chapterLocal = chapterGlobal, mangaId = 0;
            List<Manga> mangas = db.mangasFromFamily(familyId.ToString());
            mangas.OrderBy(x => x.PartNo);

            if (mangas.Count > 0)
            {
                foreach (Manga manga in mangas)
                {
                    if (chapterLocal > manga.ChapterCount)
                    {
                        chapterLocal -= manga.ChapterCount;
                    }
                    else
                    {
                        mangaId = manga.ID;
                        break;
                    }
                }

                if (mangaId == 0)
                {
                    mangaId = mangas.Last().ID;
                }
            }

            return Json(new { resultChapter = chapterLocal, mangaId = mangaId }, JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Manga Chapters Calculator/Controllers/MangasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Manga_Chapters_Calculator.Models;
using Manga_Chapters_Calculator.DAL;

namespace Manga_Chapters_Calculator.Controllers
{
    public class MangasController : Controller
    {
        private MangaContext db = new MangaContext();

        // GET: Mangas
        public ActionResult Index()
        {
            var mangas = db.mangasFromFamily(getFamilyId());
            return View(mangas);
        }

        // GET: Mangas/Details/5
        public ActionResult Details(int? partNo)
        {
            if (partNo == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manga manga = findManga(partNo);
            if (manga == null)
            {
                return HttpNotFound();
            }
            return View(manga);
        }

        // GET: Mangas/Create
        public ActionResult Create()
        {
            ViewBag.MangaFamilyID = new SelectList(db.MangaFamilies, "ID", "Name");
            return View();
        }

        // POST: Mangas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,PartNo,ChapterCount,MangaFamilyID")] Manga manga)
        {
            if (ModelState.IsValid)
            {
                db.Mangas.Add(manga);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MangaFamilyID = new SelectList(db.MangaFamilies, "ID", "Name", manga.MangaFamilyID);
            return View(manga);
        }

        // GET: Mangas/Edit/5
        public ActionResult Edit(int? partNo)
        {
            if (partNo == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manga manga = findManga(partNo);
            if (manga == null)
            {
                return HttpNotFound();
            }
            ViewBag.MangaFamilyID = new SelectList(db.MangaFamilies, "ID", "Name", manga.MangaFamilyID);
            return View(manga);
        }

        // POST: Mangas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,PartNo,ChapterCount,MangaFamilyID")] Manga manga)
        {
            if (ModelState.IsValid)
            {
                db.Entry(manga).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MangaFamilyID = new SelectList(db.MangaFamilies, "ID", "Name", manga.MangaFamilyID);
            return View(manga);
        }

        // GET: Mangas/Delete/5
        public ActionResult Delete(int? partNo)
        {
            if (partNo == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Manga manga = findManga(partNo);
            if (manga == null)
            {
                return HttpNotFound();
            }
            return View(manga);
        }

        // POST: Mangas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int partNo)
        {
            Manga manga = findManga(partNo);
            db.Mangas.Remove(manga);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult GetGlobalChapter(int chapterLocal, int mangaId)
        {
            int chapterGlobal = chapterLocal;
            Manga currentManga = db.Mangas.Find(mangaId);

            if (currentManga != null)
            {
                List<Manga> mangas = db.Mangas.Where(
                        x => x.MangaFamilyID == currentManga.MangaFamilyID &&
                        x.PartNo < currentManga.PartNo
                    ).ToList<Manga>();

                foreach(Manga manga in mangas)
                {
                    chapterGlobal += manga.ChapterCount;
                }
            }

            return Json(new { resultChapter = chapterGlobal }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        private string getFamilyId()
        {
            return Url.RequestContext.RouteData.Values["MangaFamilyID"].ToString();
        }

        private Manga findManga(int? partNo, string familyId = null)
        {
            if (familyId == null) familyId = getFamilyId();
            var mangas = db.Mangas.Where(
                element => element.MangaFamilyID.ToString() == familyId && element.PartNo == partNo
                );
            if(mangas.Count() > 0)
                return mangas.First();

            return null;
        }
    }
}

Manga Chapters Calculator/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Manga Chapters Calculator/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Manga Chapters Calculator/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Manga Chapters Calculator</h1>
    <br/>
    <p class="lead">Aplikacja służy do przeliczania "globalnego" rozdziału mangi z danej rodziny na rozdział "lokalny" dla danej jej części, oraz na odwrót (np. którym ogólnie rozdziałem Jojo jest 12 rozdział 4 części?).</p>
    <p>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <div class="form-group">
                    @Html.Label("lblFamily", "Wybierz rodzinę mang:")
                    <div class="col-md-10">
                        @Html.DropDownList("families", null, new { @style = "min-width: 300px;" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("lblManga", "Wybierz mangę:")
                    <div class="col-md-12">
                        @Html.DropDownList("mangas", null, new { @style="min-width: 300px;" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            @Html.Label("lblChapterLocal", "Numer rozdziału lokalny:")
                        </div>
                        <div class="col-sm-6">
                            @Html.Label("lblChapterGlobal", "Numer rozdziału globalny:")
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            @Html.TextBox("chapterLocal", null, new { @type = "number", @min = "1" })
                        </div>
                        <div class="col-sm-2">
                            <input type="button" value="<->" class="btn btn-default" onclick="modeSwitch()" />
                        </div>
                        <div class="col-sm-4">
                            @Html.TextBox("chapterGlobal", null, new { @type = "number", @disabled = "true", @min = "1" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="button" value="Przelicz" class="btn btn-default btn-lg" onclick="calculate()" />
                </div>
            </div>
        }
     </p>
</div>

<script>
    function modeSwitch() {
        var inpChapterGlobal= document.getElementById('chapterGlobal');
        var inpChapterLocal = document.getElementById('chapterLocal');
        var inpSelectManga = document.getElementById('mangas');

        if (inpChapterGlobal.disabled) {
            inpChapterGlobal.disabled = false;
            inpChapterLocal.disabled = true;
            inpSelectManga.disabled = true;
        }
        else {
            inpChapterGlobal.disabled = true;
            inpChapterLocal.disabled = false;
            inpSelectManga.disabled = false;
        }
    }
</script>

<script>
    function calculate() {
        var inputControl, outputControl;
        var mangasListControl = document.getElementById('mangas');
        var familiesListControl = document.getElementById('families');

        if (document.getElementById('chapterLocal').disabled) {
            inputControl = document.getElementById('chapterGlobal');
            outputControl = document.getElementById('chapterLocal');

            $.ajax({
                type: "POST",
                dataType: 'json',
                cache: false,
                url: '@Url.Action("GetLocalChapter", "MangaFamilies")',
                data: {
                    chapterGlobal: inputControl.value,
                    familyId: familiesListControl.options[familiesListControl.selectedIndex].value
                },
                success: function (response) {
                    outputControl.value = response.resultChapter;
                    mangasListControl.value = response.mangaId;
                }
            });
        }
        else {
            inputControl = document.getElementById('chapterLocal');
            outputControl = document.getElementById('chapterGlobal');
            
            $.ajax({
                type: "POST",
                dataType: 'json',
                cache: false,
                url: '@Url.Action("GetGlobalChapter", "Mangas")',
                data: {
                    chapterLocal: inputControl.value, 
                    mangaId: mangasListControl.options[mangasListControl.selectedIndex].value 
                },
                success: function (response) {
                    outputControl.value = response.resultChapter;
                }
            });
        }
    }

</script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#families').change(function () {
            var selectedFamily = $('#families').val();

            $.ajax({
                type: "POST",
                url: '@Url.Action("Mangas", "Home")',
                data: { familyId: selectedFamily },
                success: function (response) {    
                    var mangasSelect = $('#mangas');
                    mangasSelect.empty();
                    $.each(response, function (i, manga) {
                        mangasSelect.append($('<option/>', {
                            value: manga.Id,
                            text: manga.Name
                        }));
                    });
                }
            })
        });
    });
</script>